project = 'Aquaticus Docs'
copyright = '2023, Aquaticus'
author = 'aquaticus'
extensions = ['sphinx_copybutton']
templates_path = ['_templates']
exclude_patterns = []
html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']
source_suffix = {'.rst': 'restructuredtext'}
html_show_sphinx=False
html_show_sourcelink = False
